services:
  backend:
    container_name: backend-laravel-php
    build:
      context: backend-laravel-php
    ports:  
      - "8000:8000"

  frontend:
    container_name: frontend-next-react
    build:
      context: frontend-next-react
    ports:  
      - "3000:3000"
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_API_URL: http://backend-laravel-php:8000/api/
      API_KEY: 123456
